language: objective-c
osx_image: xcode7.2

before_install:
  - gem install cocoapods
  - gem install xcpretty

script:
  - set -o pipefail
  - pod lib lint --allow-warnings
  - xcodebuild -scheme "DRAsyncOperations Mac" test | xcpretty
  - xcodebuild -scheme "DRAsyncOperations iOS" -sdk iphonesimulator  -destination "platform=iOS Simulator,name=iPhone 6s" test | xcpretty
  - xcodebuild -scheme "DRAsyncOperations tvOS" -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" test | xcpretty
  - xcodebuild -scheme "DRAsyncOperations watchOS" -sdk watchsimulator   -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" build | xcpretty
